
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        url: jdbc:mysql://localhost:3300/aaa?createDatabaseIfNotExist=true&useSSL=false
        password: 'root'
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: create
server:
    port: '8083'